language: "python"
python:
  - "3.2"
  - "3.3"
before_install:
  - "make setup"
  - "source ~/virtualenv/python3.3/bin/activate"
  - "python --version"
install:
  - "make install"
script:
  - "make travis"
matrix:
  allow_failures:
    - python: "3.2"
